### ISSUE TITLE
error[E0425]: cannot find value `Mark` in module `sockopt`

### ISSUE THREAD

**Issue by briteming** [optman/minivtun-rs#1]
hi.

on my mac.
yudeMacBook-Air:minivtun-rs ym$ cargo build --release

it exports:
...
Compiling minivtun-rs v0.1.0 (/Users/ym/minivtun-rs)
error[E0425]: cannot find value `Mark` in module `sockopt`
  --> src/main.rs:67:49
   |
67 |         setsockopt(socket.as_raw_fd(), sockopt::Mark, &fwmark)?;
   |                                                 ^^^^ not found in `sockopt`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `minivtun-rs` due to previous error
yudeMacBook-Air:minivtun-rs ym$

how to fix it?

**Comment by optman** [comment]
look like fwmark is linux only feature, you can comment out this line.

**Comment by briteming** [comment]
在哪里comment out this line？没看见地方。

**Comment by optman** [comment]
// setsockopt(socket.as_raw_fd(), sockopt::Mark, &fwmark)?;

**Comment by briteming** [comment]
删掉这行：setsockopt(socket.as_raw_fd(), sockopt::Mark, &fwmark)?;
果然 编译成功。
