### ISSUE TITLE
"invalid local ipv4 address"?

### ISSUE THREAD

**Issue by briteming** [optman/minivtun-rs#2]
hi.

on my linux vps,
root@racknerd-7b97d8:~/minivtun-rs/target/release# ./minivtun-rs --ifname mvr --ipv4-addr 10.20.10.1 --key mykey --local 0.0.0.0:2189 --mtu 1200 --type aes-256
Error: InvalidArg("invalid local ipv4 address")
root@racknerd-7b97d8:~/minivtun-rs/target/release# ./minivtun-rs --ifname mvr --ipv4-addr 192.20.10.1 --key mykey --local 0.0.0.0:2189 --mtu 1200 --type aes-256
Error: InvalidArg("invalid local ipv4 address")
root@racknerd-7b97d8:~/minivtun-rs/target/release#

怎么设置有效的ipv4 address？

**Comment by optman** [comment]
usage example, please refer origin [minivtun](https://github.com/rssnsj/minivtun)

**Comment by briteming** [comment]
hi。
我看了https://github.com/rssnsj/minivtun ，在服务器上的命令运行成功。
但在mac上，还是失败：
yudeMacBook-Air:release ym$ sudo ./minivtun-rs -r vps-public-ip:2189 -a 10.20.10.2/24 --key mykey
Error: InvalidName
yudeMacBook-Air:release ym$

怎么解决InvalidName？

**Comment by briteming** [comment]
hi.
实在不明白InvalidName是什么错误？我客户端命令没写错啊。
能回复我吗？
非常感谢！

**Comment by optman** [comment]
首先， minivtun-rs代码里没有抛出这个InvalidName这个错误，所以应该是更底层库的错误。从直觉来看，很有可能是vps-public-ip域名解析失败，你可以用ip试试。
其次，开源代码放在github上，只供参考，请自行研究代码解决自己遇到的问题。如果发现是代码的问题，可以提Bug。如果是使用方面的问题，请寻求搜索引擎或其它论坛的帮助。

**Comment by briteming** [comment]
hi.
vps-public-ip代表我的服务器的公网ip,我没有写成域名。
你说“ minivtun-rs代码里没有抛出这个InvalidName这个错误‘，我以为是 minivtun代码里抛出这个InvalidName错误，但是我clone了minivtun的代码，并用grep命令查找字符串InvalidName：
yudeMacBook-Air:minivtun ym$ grep -rn InvalidName .
yudeMacBook-Air:minivtun ym$ grep -rn InvalidName *
yudeMacBook-Air:minivtun ym$

真不明白InvalidName到底是从哪里冒出来的。楼主可否深入研究一下？难道是mac系统造成了这一错误？
我安装过minivtun，用它翻wall没有问题。

**Comment by optman** [comment]
没Mac机器，爱莫能助

briteming ***@***.***> 于 2022年4月30日周六 17:54写道：
